[2025-02-26 10:39:24,154: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 10:39:24,161: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 10:39:24,165: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 10:39:24,168: INFO: common: created directory at: artifacts]
[2025-02-26 10:39:24,171: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 10:39:26,396: INFO: data_ingestion: File downloaded at artifacts/data_ingestion/data.zip]
[2025-02-26 10:39:26,517: ERROR: data_ingestion: Downloaded file is not a valid ZIP file.]
[2025-02-26 10:39:26,519: ERROR: main: Failed to execute data_ingestion pipeline]
[2025-02-26 10:39:26,520: ERROR: main: Downloaded file is not a ZIP file]
[2025-02-26 10:39:26,521: INFO: main: Logging is done]
[2025-02-26 10:42:47,950: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 10:42:47,956: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 10:42:47,959: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 10:42:47,961: INFO: common: created directory at: artifacts]
[2025-02-26 10:42:47,962: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 10:42:47,963: INFO: data_ingestion: File already exists at artifacts/data_ingestion/data.zip]
[2025-02-26 10:42:47,968: ERROR: data_ingestion: Downloaded file is not a valid ZIP file.]
[2025-02-26 10:42:47,969: ERROR: main: Failed to execute data_ingestion pipeline]
[2025-02-26 10:42:47,970: ERROR: main: Downloaded file is not a ZIP file]
[2025-02-26 10:42:47,970: INFO: main: Logging is done]
[2025-02-26 10:47:58,173: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 10:47:58,179: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 10:47:58,183: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 10:47:58,185: INFO: common: created directory at: artifacts]
[2025-02-26 10:47:58,188: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 10:48:03,209: INFO: data_ingestion: File downloaded at artifacts/data_ingestion/data.zip]
[2025-02-26 10:48:03,723: INFO: data_ingestion: Extracted zip file to artifacts/data_ingestion]
[2025-02-26 10:48:03,724: INFO: stage_1_pipelinedataIngestion: Data Ingestion process completed successfully]
[2025-02-26 10:48:03,725: INFO: main: Completed data_ingestion pipeline]
[2025-02-26 10:48:03,726: INFO: main: Logging is done]
[2025-02-26 10:48:23,591: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 10:48:23,597: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 10:48:23,601: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 10:48:23,603: INFO: common: created directory at: artifacts]
[2025-02-26 10:48:23,605: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 10:48:28,276: INFO: data_ingestion: File downloaded at artifacts/data_ingestion/data.zip]
[2025-02-26 10:48:28,656: INFO: data_ingestion: Extracted zip file to artifacts/data_ingestion]
[2025-02-26 10:48:28,657: INFO: stage_1_pipelinedataIngestion: Data Ingestion process completed successfully]
[2025-02-26 10:48:28,658: INFO: main: Completed data_ingestion pipeline]
[2025-02-26 10:48:28,659: INFO: main: Logging is done]
[2025-02-26 13:34:18,700: INFO: config: PyTorch version 2.6.0 available.]
[2025-02-26 13:57:58,286: INFO: common: yaml file: c:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 13:57:58,302: INFO: common: yaml file: c:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 13:57:58,308: INFO: common: created directory at: artifacts]
[2025-02-26 13:57:58,319: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-26 14:02:06,504: INFO: common: yaml file: c:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 14:02:06,510: INFO: common: yaml file: c:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 14:02:06,514: INFO: common: created directory at: artifacts]
[2025-02-26 14:02:06,519: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-26 14:15:30,659: INFO: config: PyTorch version 2.6.0 available.]
[2025-02-26 14:18:39,987: INFO: config: PyTorch version 2.6.0 available.]
[2025-02-26 14:20:00,784: INFO: config: PyTorch version 2.6.0 available.]
[2025-02-26 14:23:00,756: INFO: config: PyTorch version 2.6.0 available.]
[2025-02-26 14:29:38,067: INFO: config: PyTorch version 2.6.0 available.]
[2025-02-26 14:31:53,668: INFO: config: PyTorch version 2.6.0 available.]
[2025-02-26 14:31:57,211: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 14:31:57,225: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 14:31:57,236: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 14:31:57,239: INFO: common: created directory at: artifacts]
[2025-02-26 14:31:57,241: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 14:32:02,151: INFO: data_ingestion: File downloaded at artifacts/data_ingestion/data.zip]
[2025-02-26 14:32:02,524: INFO: data_ingestion: Extracted zip file to artifacts/data_ingestion]
[2025-02-26 14:32:02,525: INFO: stage_1_pipelinedataIngestion: Data Ingestion process completed successfully]
[2025-02-26 14:32:02,526: INFO: main: Completed data_ingestion pipeline]
[2025-02-26 14:32:02,526: INFO: main: Logging is done]
[2025-02-26 14:32:02,527: INFO: main: Initiating data_transformation pipeline]
[2025-02-26 14:32:02,534: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 14:32:02,538: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 14:32:02,540: INFO: common: created directory at: artifacts]
[2025-02-26 14:32:02,543: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-26 14:32:23,224: INFO: main: Completed data_transformation pipeline]
[2025-02-26 14:32:23,225: INFO: main: Logging is done]
[2025-02-26 14:39:09,457: INFO: fake_tensor: FakeTensor cache stats:]
[2025-02-26 14:39:09,458: INFO: fake_tensor:   cache_hits: 0]
[2025-02-26 14:39:09,459: INFO: fake_tensor:   cache_misses: 0]
[2025-02-26 14:39:42,940: INFO: config: PyTorch version 2.6.0 available.]
[2025-02-26 14:39:46,399: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 14:39:46,405: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 14:39:46,409: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 14:39:46,411: INFO: common: created directory at: artifacts]
[2025-02-26 14:39:46,413: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 14:39:46,414: INFO: data_ingestion: File already exists at artifacts/data_ingestion/data.zip]
[2025-02-26 14:39:46,735: INFO: data_ingestion: Extracted zip file to artifacts/data_ingestion]
[2025-02-26 14:39:46,736: INFO: stage_1_pipelinedataIngestion: Data Ingestion process completed successfully]
[2025-02-26 14:39:46,737: INFO: main: Completed data_ingestion pipeline]
[2025-02-26 14:39:46,737: INFO: main: Logging is done]
[2025-02-26 14:39:46,738: INFO: main: Initiating data_transformation pipeline]
[2025-02-26 14:39:46,745: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 14:39:46,749: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 14:39:46,751: INFO: common: created directory at: artifacts]
[2025-02-26 14:39:46,754: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-26 14:39:46,755: ERROR: main: Failed to execute data_transformation pipeline]
[2025-02-26 14:39:46,756: ERROR: main: DataTransformationConfig.__init__() got an unexpected keyword argument 'datadir']
[2025-02-26 14:39:46,757: INFO: main: Logging is done]
[2025-02-26 14:55:40,127: INFO: config: PyTorch version 2.6.0 available.]
[2025-02-26 14:55:43,688: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 14:55:43,694: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 14:55:43,698: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 14:55:43,700: INFO: common: created directory at: artifacts]
[2025-02-26 14:55:43,701: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 14:55:43,702: INFO: data_ingestion: File already exists at artifacts/data_ingestion/data.zip]
[2025-02-26 14:55:44,031: INFO: data_ingestion: Extracted zip file to artifacts/data_ingestion]
[2025-02-26 14:55:44,032: INFO: stage_1_pipelinedataIngestion: Data Ingestion process completed successfully]
[2025-02-26 14:55:44,033: INFO: main: Completed data_ingestion pipeline]
[2025-02-26 14:55:44,033: INFO: main: Logging is done]
[2025-02-26 14:55:44,034: INFO: main: Initiating data_transformation pipeline]
[2025-02-26 14:55:44,042: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 14:55:44,046: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 14:55:44,049: INFO: common: created directory at: artifacts]
[2025-02-26 14:55:44,051: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-26 14:56:03,273: INFO: main: Completed data_transformation pipeline]
[2025-02-26 14:56:03,274: INFO: main: Logging is done]
[2025-02-26 15:16:48,808: INFO: config: PyTorch version 2.6.0 available.]
[2025-02-26 15:16:52,201: INFO: main: Initiating data_ingestion pipeline]
[2025-02-26 15:16:52,208: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 15:16:52,212: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 15:16:52,215: INFO: common: created directory at: artifacts]
[2025-02-26 15:16:52,217: INFO: common: created directory at: artifacts/data_ingestion]
[2025-02-26 15:16:52,218: INFO: data_ingestion: File already exists at artifacts/data_ingestion/data.zip]
[2025-02-26 15:16:52,554: INFO: data_ingestion: Extracted zip file to artifacts/data_ingestion]
[2025-02-26 15:16:52,555: INFO: stage_1_pipelinedataIngestion: Data Ingestion process completed successfully]
[2025-02-26 15:16:52,556: INFO: main: Completed data_ingestion pipeline]
[2025-02-26 15:16:52,556: INFO: main: Logging is done]
[2025-02-26 15:16:52,558: INFO: main: Initiating data_transformation pipeline]
[2025-02-26 15:16:52,564: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\config\config.yaml loaded successfully]
[2025-02-26 15:16:52,567: INFO: common: yaml file: C:\Fythonn\fyt\Main\Project_4\params.yaml loaded successfully]
[2025-02-26 15:16:52,569: INFO: common: created directory at: artifacts]
[2025-02-26 15:16:52,571: INFO: common: created directory at: artifacts/data_transformation]
[2025-02-26 15:16:56,951: INFO: data_transformation: Data Transformation process completed successfully]
[2025-02-26 15:16:57,084: INFO: main: Completed data_transformation pipeline]
[2025-02-26 15:16:57,085: INFO: main: Logging is done]
